### ISSUE TITLE
aqsis not build with OpenEXR 2.0.1

### ISSUE THREAD

**Issue by nemysis** [aqsis/aqsis#3]
Hello i am FreeBSD developer for ilmbase and OpenEXR

http://www.freshports.org/graphics/ilmbase/

http://www.freshports.org/graphics/OpenEXR/

aqais build failures with OpenEXR 2.01

``` \n
[ 57%] Building CXX object libs/tex/CMakeFiles/aqsis_tex.dir/maketexture/bake.cpp.o
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:177:23: error: allocation of incomplete type 'Imf::InputFile'
                m_exrFile.reset(new Imf::InputFile(native(fileName).c_str()));
                                    ^~~~~~~~~~~~~~
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:183:25: error: member access into incomplete type 'Imf::InputFile
'
        convertHeader(m_exrFile->header(), m_header);
                               ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:197:18: error: member access into incomplete type 'Imf::InputFil$
'
        return m_exrFile->fileName();
                        ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:204:44: error: member access into incomplete type 'Imf::InputFil$
'
        const Imath::Box2i& dataWindow = m_exrFile->header().dataWindow();
                                                  ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:227:11: error: member access into incomplete type 'Imf::InputFil$
'
        m_exrFile->setFrameBuffer(frameBuffer);
                 ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.cpp:229:11: error: member access into incomplete type 'Imf::InputFile
'
        m_exrFile->readPixels(startLine, startLine + numScanlines - 1);
                 ^
/usr/local/ports/local/In-Review/graphics/aqsis/work/aqsis-1.8.2/libs/tex/io/exrinputfile.h:53:8: note: forward declaration of 'Imf::InputFile'
        class InputFile;
              ^
[ 58%] Building CXX object libs/tex/CMakeFiles/aqsis_tex.dir/maketexture/maketexture.cpp.o
[ 58%] Building CXX object libs/tex/CMakeFiles/aqsis_tex.dir/pointcloud/pointcloud.cpp.o
6 errors generated.
*** [libs/tex/CMakeFiles/aqsis_tex.dir/io/exrinputfile.cpp.o] Error code 1
1 error
*** [libs/tex/CMakeFiles/aqsis_tex.dir/all] Error code 2
1 error
*** [all] Error code 2
1 error
===> Compilation failed unexpectedly.
```

Please solve build failures. and release new version 1.8.3.
